# Based on the following mkdocs.yml's:
# - https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml
# - https://github.com/facelessuser/pymdown-extensions/blob/master/docs/src/mkdocs.yml

site_name: The Internals of Delta Lake
site_url: https://books.japila.pl/delta-lake-internals/
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of Delta Lake

# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/
repo_name: delta-lake-internals
repo_url: https://github.com/japila-books/delta-lake-internals
edit_uri: edit/master/docs/

copyright: |
  Copyright &copy; 2020 <a href="https://twitter.com/jaceklaskowski" target="_blank" rel="noopener">Jacek Laskowski</a>

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  # the following two lines don't seem to work on ReadTheDocs
  # https://github.com/readthedocs/readthedocs.org/issues/6889
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date:
      enabled_if_env: CI
  - awesome-pages
  - macros

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
  delta:
    version: 0.7.0
  hadoop:
    version: 2.7.4
    api: https://hadoop.apache.org/docs/r2.7.4/api
  book:
    spark_sql: https://jaceklaskowski.github.io/mastering-spark-sql-book

google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto

nav:
  - Home:
    - Welcome: index.md
    - Overview: overview.md
    - Installation: installation.md
    - Time Travel:
      - Time Travel: time-travel.md
      - DeltaTimeTravelSpec: DeltaTimeTravelSpec.md
    - DeltaTable: DeltaTable.md
    - Configuration Properties: DeltaSQLConf.md
    - Transaction Log (DeltaLog):
      - DeltaLog: DeltaLog.md
      - Operation: Operation.md
      - Checkpoints: Checkpoints.md
      - SnapshotManagement: SnapshotManagement.md
      - ReadChecksum: ReadChecksum.md
      - MetadataCleanup: MetadataCleanup.md
      - LogStoreProvider: LogStoreProvider.md
      - VerifyChecksum: VerifyChecksum.md
    - State Snapshot:
      - Snapshot: Snapshot.md
      - InMemoryLogReplay: InMemoryLogReplay.md
      - PartitionFiltering: PartitionFiltering.md
      - DeltaFileFormat: DeltaFileFormat.md
    - OptimisticTransaction:
      - OptimisticTransaction: OptimisticTransaction.md
      - TransactionalWrite: TransactionalWrite.md
      - DelayedCommitProtocol: DelayedCommitProtocol.md
      - Post-Commit Hooks: PostCommitHook.md
      - OptimisticTransactionImpl: OptimisticTransactionImpl.md
    - LogStore:
      - LogStore: LogStore.md
      - HDFSLogStore: HDFSLogStore.md
      - HadoopFileSystemLogStore: HadoopFileSystemLogStore.md
    - DeltaHistoryManager: DeltaHistoryManager.md
    - Actions:
      - Action: Action.md
      - AddFile: AddFile.md
      - CommitInfo: CommitInfo.md
      - FileAction: FileAction.md
      - Metadata: Metadata.md
      - Protocol: Protocol.md
      - RemoveFile: RemoveFile.md
      - SetTransaction: SetTransaction.md
      - SingleAction: SingleAction.md
    - DeltaConfigs:
      - DeltaConfigs: DeltaConfigs.md
      - DeltaConfig: DeltaConfig.md
    - FileNames: FileNames.md
    - Logging: spark-logging.md
    - Delta Data Source:
      - DeltaDataSource: DeltaDataSource.md
      - DeltaOptions: DeltaOptions.md
      - DeltaSource:
        - DeltaSource: DeltaSource.md
        - DeltaSourceOffset: DeltaSourceOffset.md
        - SnapshotIterator: SnapshotIterator.md
        - DeltaSourceSnapshot: DeltaSourceSnapshot.md
      - DeltaSink: DeltaSink.md
    - Spark SQL Extensions:
      - DeltaCatalog: DeltaCatalog.md
      - DeltaTableV2: DeltaTableV2.md
      - StagedDeltaTableV2: StagedDeltaTableV2.md
      - DeltaSparkSessionExtension: DeltaSparkSessionExtension.md
      - DeltaAnalysis: DeltaAnalysis.md
      - DeltaUnsupportedOperationsCheck: DeltaUnsupportedOperationsCheck.md
      - PreprocessTableDelete: PreprocessTableDelete.md
      - PreprocessTableMerge: PreprocessTableMerge.md
      - PreprocessTableUpdate: PreprocessTableUpdate.md
    - SQLMetricsReporting: SQLMetricsReporting.md
    - DeltaConvert: DeltaConvert.md
    - File Indices:
      - TahoeFileIndex: TahoeFileIndex.md
      - TahoeBatchFileIndex: TahoeBatchFileIndex.md
      - TahoeLogFileIndex: TahoeLogFileIndex.md
      - DeltaLogFileIndex: DeltaLogFileIndex.md
  - Delta SQL:
    - Delta SQL: sql/index.md
    - DeltaSqlParser: sql/DeltaSqlParser.md
    - DeltaSqlAstBuilder: sql/DeltaSqlAstBuilder.md
  - Commands:
    - DeltaCommand: commands/DeltaCommand.md
    - Alter Table:
      - AlterDeltaTableCommand: commands/AlterDeltaTableCommand.md
      - AlterTableAddColumnsDeltaCommand: commands/AlterTableAddColumnsDeltaCommand.md
      - AlterTableChangeColumnDeltaCommand: commands/AlterTableChangeColumnDeltaCommand.md
      - AlterTableReplaceColumnsDeltaCommand: commands/AlterTableReplaceColumnsDeltaCommand.md
      - AlterTableSetLocationDeltaCommand: commands/AlterTableSetLocationDeltaCommand.md
      - AlterTableSetPropertiesDeltaCommand: commands/AlterTableSetPropertiesDeltaCommand.md
      - AlterTableUnsetPropertiesDeltaCommand: commands/AlterTableUnsetPropertiesDeltaCommand.md
    - ConvertToDeltaCommand: commands/ConvertToDeltaCommand.md
    - CreateDeltaTableCommand: commands/CreateDeltaTableCommand.md
    - DeleteCommand: commands/DeleteCommand.md
    - DeltaGenerateCommand:
      - DeltaGenerateCommand: commands/DeltaGenerateCommand.md
      - DeltaGenerateCommandBase: DeltaGenerateCommandBase.md
      - GenerateSymlinkManifest: GenerateSymlinkManifest.md
    - DescribeDeltaDetailCommand: commands/DescribeDeltaDetailCommand.md
    - DescribeDeltaHistoryCommand: commands/DescribeDeltaHistoryCommand.md
    - Merge:
      - DeltaMergeBuilder: commands/DeltaMergeBuilder.md
      - DeltaMergeMatchedActionBuilder: commands/DeltaMergeMatchedActionBuilder.md
      - DeltaMergeNotMatchedActionBuilder: commands/DeltaMergeNotMatchedActionBuilder.md
      - DeltaMergeIntoClause: commands/DeltaMergeIntoClause.md
      - DeltaMergeInto: commands/DeltaMergeInto.md
      - MergeIntoCommand: commands/MergeIntoCommand.md
      - JoinedRowProcessor: commands/JoinedRowProcessor.md
    - UpdateCommand: commands/UpdateCommand.md
    - Vacuum:
      - Vacuum: commands/vacuum.md
      - VacuumCommand: commands/VacuumCommand.md
      - VacuumCommandImpl: commands/VacuumCommandImpl.md
      - VacuumTableCommand: commands/VacuumTableCommand.md
    - WriteIntoDelta: commands/WriteIntoDelta.md
  - Demos:
    - Merge Operation: demo/merge-operation.md
    - Converting Parquet Dataset Into Delta Format: demo/Converting-Parquet-Dataset-Into-Delta-Format.md
    - Stream Processing of Delta Table: demo/stream-processing-of-delta-table.md
    - Using Delta Lake as Streaming Sink in Structured Streaming: demo/Using-Delta-Lake-as-Streaming-Sink-in-Structured-Streaming.md
    - Debugging Delta Lake Using IntelliJ IDEA: demo/Debugging-Delta-Lake-Using-IntelliJ-IDEA.md
    - Observing Transaction Retries: demo/Observing-Transaction-Retries.md
    - DeltaTable, DeltaLog And Snapshots: demo/DeltaTable-DeltaLog-And-Snapshots.md
    - Schema Evolution: demo/schema-evolution.md
    - Using User Metadata to Distinguish Commits of Streaming Queries: demo/using-user-metadata-to-distinguish-commits-streaming-queries.md
  - Misc:
    - DeltaErrors: DeltaErrors.md
    - DeltaFileOperations: DeltaFileOperations.md
    - DeltaInvariantCheckerExec: DeltaInvariantCheckerExec.md
    - DeltaTableOperations: DeltaTableOperations.md
    - DeltaTableUtils: DeltaTableUtils.md
    - ImplicitMetadataOperation: ImplicitMetadataOperation.md
    - Invariants: Invariants.md
    - SchemaUtils: SchemaUtils.md
    - StateCache:
      - StateCache: StateCache.md
      - CachedDS: CachedDS.md
  - Contenders:
    - Contenders: contenders/index.md
