site_name: The Internals of Delta Lake
site_url: https://books.japila.pl/delta-lake-internals/
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of Delta Lake

repo_name: delta-lake-internals
repo_url: https://github.com/japila-books/delta-lake-internals
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2021 Jacek Laskowski

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - git-revision-date:
      enabled_if_env: CI
  - awesome-pages
  - macros

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
  book:
    title: Delta Lake
    spark_sql: https://jaceklaskowski.github.io/mastering-spark-sql-book
    structured_streaming: https://jaceklaskowski.github.io/spark-structured-streaming-book
    spark_core: https://books.japila.pl/apache-spark-internals
  delta:
    version: 1.0.0-SNAPSHOT
    github: https://github.com/delta-io/delta/blob/master
    commit: https://github.com/delta-io/delta/commit
  hadoop:
    version: 3.2.0
    docs: https://hadoop.apache.org/docs/r3.2.0
    api: https://hadoop.apache.org/docs/r3.2.0/api
  jackson:
    github: https://github.com/FasterXML/jackson
    scala: https://github.com/FasterXML/jackson-module-scala
  java:
    api: https://docs.oracle.com/en/java/javase/11/docs/api
  scala:
    version: 2.12.10
    api: https://www.scala-lang.org/api/2.12.10
    docs: https://docs.scala-lang.org/

google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto

nav:
  - Home: index.md
  - Internals:
    - Overview: overview.md
    - Installation: installation.md
    - Time Travel:
      - Time Travel: time-travel.md
      - DeltaTimeTravelSpec: DeltaTimeTravelSpec.md
    - DeltaTableIdentifier: DeltaTableIdentifier.md
    - Configuration Properties:
      - Configuration Properties: configuration-properties.md
      - DeltaSQLConf: DeltaSQLConf.md
    - Table Properties:
      - Table Properties: table-properties.md
      - DeltaConfigs: DeltaConfigs.md
      - DeltaConfig: DeltaConfig.md
    - Transaction Log (DeltaLog):
      - DeltaLog: DeltaLog.md
      - Operation: Operation.md
      - Checkpoints: Checkpoints.md
      - SnapshotManagement: SnapshotManagement.md
      - ReadChecksum: ReadChecksum.md
      - MetadataCleanup: MetadataCleanup.md
      - VerifyChecksum: VerifyChecksum.md
    - Optimistic Transactions:
      - OptimisticTransaction: OptimisticTransaction.md
      - OptimisticTransactionImpl: OptimisticTransactionImpl.md
      - TransactionalWrite: TransactionalWrite.md
      - DelayedCommitProtocol: DelayedCommitProtocol.md
      - IsolationLevel: IsolationLevel.md
      - Post-Commit Hooks: PostCommitHook.md
    - State Snapshot:
      - Snapshot: Snapshot.md
      - InMemoryLogReplay: InMemoryLogReplay.md
      - PartitionFiltering: PartitionFiltering.md
      - DeltaFileFormat: DeltaFileFormat.md
    - DeltaHistoryManager: DeltaHistoryManager.md
    - LogStore:
      - LogStore: LogStore.md
      - LogStoreProvider: LogStoreProvider.md
      - HDFSLogStore: HDFSLogStore.md
      - HadoopFileSystemLogStore: HadoopFileSystemLogStore.md
      - S3SingleDriverLogStore: S3SingleDriverLogStore.md
    - Actions:
      - Action: Action.md
      - AddCDCFile: AddCDCFile.md
      - AddFile: AddFile.md
      - CommitInfo: CommitInfo.md
      - FileAction: FileAction.md
      - Metadata: Metadata.md
      - Protocol: Protocol.md
      - RemoveFile: RemoveFile.md
      - SetTransaction: SetTransaction.md
      - SingleAction: SingleAction.md
    - FileNames: FileNames.md
    - Logging: spark-logging.md
    - Delta Data Source:
      - DeltaDataSource: DeltaDataSource.md
      - Options:
        - Options: options.md
        - DeltaOptions: DeltaOptions.md
        - DeltaOptionParser: DeltaOptionParser.md
        - DeltaReadOptions: DeltaReadOptions.md
        - DeltaWriteOptions: DeltaWriteOptions.md
        - DeltaWriteOptionsImpl: DeltaWriteOptionsImpl.md
      - DeltaSource:
        - DeltaSource: DeltaSource.md
        - DeltaSourceOffset: DeltaSourceOffset.md
        - DeltaSourceSnapshot: DeltaSourceSnapshot.md
        - SnapshotIterator: SnapshotIterator.md
        - AdmissionLimits: AdmissionLimits.md
      - DeltaSink: DeltaSink.md
      - WriteIntoDeltaBuilder: WriteIntoDeltaBuilder.md
    - Spark SQL Extensions:
      - DeltaCatalog: DeltaCatalog.md
      - DeltaTableV2: DeltaTableV2.md
      - StagedDeltaTableV2: StagedDeltaTableV2.md
      - DeltaSparkSessionExtension: DeltaSparkSessionExtension.md
      - DeltaAnalysis: DeltaAnalysis.md
      - DeltaUnsupportedOperationsCheck: DeltaUnsupportedOperationsCheck.md
      - PreprocessTableDelete: PreprocessTableDelete.md
      - PreprocessTableMerge: PreprocessTableMerge.md
      - PreprocessTableUpdate: PreprocessTableUpdate.md
      - ActiveOptimisticTransactionRule: ActiveOptimisticTransactionRule.md
    - SQLMetricsReporting: SQLMetricsReporting.md
    - DeltaConvert: DeltaConvert.md
    - File Indices:
      - TahoeFileIndex: TahoeFileIndex.md
      - PinnedTahoeFileIndex: PinnedTahoeFileIndex.md
      - TahoeBatchFileIndex: TahoeBatchFileIndex.md
      - TahoeLogFileIndex: TahoeLogFileIndex.md
      - DeltaLogFileIndex: DeltaLogFileIndex.md
  - APIs:
    - DeltaTable: DeltaTable.md
  - Delta SQL:
    - Delta SQL: sql/index.md
    - DeltaSqlParser: sql/DeltaSqlParser.md
    - DeltaSqlAstBuilder: sql/DeltaSqlAstBuilder.md
  - Commands:
    - commands/index.md
    - DeltaCommand: commands/DeltaCommand.md
    - Alter Table:
      - AlterDeltaTableCommand: commands/AlterDeltaTableCommand.md
      - AlterTableAddColumnsDeltaCommand: commands/AlterTableAddColumnsDeltaCommand.md
      - AlterTableAddConstraintDeltaCommand: commands/AlterTableAddConstraintDeltaCommand.md
      - AlterTableChangeColumnDeltaCommand: commands/AlterTableChangeColumnDeltaCommand.md
      - AlterTableDropConstraintDeltaCommand: commands/AlterTableDropConstraintDeltaCommand.md
      - AlterTableReplaceColumnsDeltaCommand: commands/AlterTableReplaceColumnsDeltaCommand.md
      - AlterTableSetLocationDeltaCommand: commands/AlterTableSetLocationDeltaCommand.md
      - AlterTableSetPropertiesDeltaCommand: commands/AlterTableSetPropertiesDeltaCommand.md
      - AlterTableUnsetPropertiesDeltaCommand: commands/AlterTableUnsetPropertiesDeltaCommand.md
    - Convert to Delta:
      - commands/convert/index.md
      - ConvertToDeltaCommand: commands/convert/ConvertToDeltaCommand.md
      - FileManifest: commands/convert/FileManifest.md
      - ManualListingFileManifest: commands/convert/ManualListingFileManifest.md
      - MetadataLogFileManifest: commands/convert/MetadataLogFileManifest.md
    - CreateDeltaTableCommand: commands/CreateDeltaTableCommand.md
    - Delete:
      - commands/delete/index.md
      - DeleteCommand: commands/delete/DeleteCommand.md
      - DeltaDelete: commands/delete/DeltaDelete.md
    - DeltaGenerateCommand:
      - DeltaGenerateCommand: commands/DeltaGenerateCommand.md
      - GenerateSymlinkManifest: GenerateSymlinkManifest.md
    - DescribeDeltaDetailCommand: commands/DescribeDeltaDetailCommand.md
    - DescribeDeltaHistoryCommand: commands/DescribeDeltaHistoryCommand.md
    - Merge:
      - DeltaMergeBuilder: commands/DeltaMergeBuilder.md
      - DeltaMergeMatchedActionBuilder: commands/DeltaMergeMatchedActionBuilder.md
      - DeltaMergeNotMatchedActionBuilder: commands/DeltaMergeNotMatchedActionBuilder.md
      - DeltaMergeIntoClause: commands/DeltaMergeIntoClause.md
      - DeltaMergeInto: commands/DeltaMergeInto.md
      - MergeIntoCommand: commands/MergeIntoCommand.md
      - JoinedRowProcessor: commands/JoinedRowProcessor.md
    - Update:
      - commands/update/index.md
      - UpdateCommand: commands/update/UpdateCommand.md
      - DeltaUpdateTable: commands/update/DeltaUpdateTable.md
    - Vacuum:
      - commands/vacuum/index.md
      - VacuumCommand: commands/vacuum/VacuumCommand.md
      - VacuumCommandImpl: commands/vacuum/VacuumCommandImpl.md
      - VacuumTableCommand: commands/vacuum/VacuumTableCommand.md
    - WriteIntoDelta: commands/WriteIntoDelta.md
  - Demos:
    - demo/index.md
    - Vacuum: demo/vacuum.md
    - dataChange: demo/dataChange.md
    - replaceWhere: demo/replaceWhere.md
    - Merge Operation: demo/merge-operation.md
    - Converting Parquet Dataset Into Delta Format: demo/Converting-Parquet-Dataset-Into-Delta-Format.md
    - Stream Processing of Delta Table: demo/stream-processing-of-delta-table.md
    - Using Delta Lake as Streaming Sink in Structured Streaming: demo/Using-Delta-Lake-as-Streaming-Sink-in-Structured-Streaming.md
    - Debugging Delta Lake Using IntelliJ IDEA: demo/Debugging-Delta-Lake-Using-IntelliJ-IDEA.md
    - Observing Transaction Retries: demo/Observing-Transaction-Retries.md
    - DeltaTable, DeltaLog And Snapshots: demo/DeltaTable-DeltaLog-And-Snapshots.md
    - Schema Evolution: demo/schema-evolution.md
    - User Metadata for Labelling Commits: demo/user-metadata-for-labelling-commits.md
  - Misc:
    - AlterTableAddConstraintStatement: AlterTableAddConstraintStatement.md
    - AlterTableDropConstraintStatement: AlterTableDropConstraintStatement.md
    - DeltaErrors: DeltaErrors.md
    - DeltaFileOperations: DeltaFileOperations.md
    - DeltaInvariantCheckerExec: DeltaInvariantCheckerExec.md
    - DeltaTableOperations: DeltaTableOperations.md
    - DeltaTableUtils: DeltaTableUtils.md
    - ImplicitMetadataOperation: ImplicitMetadataOperation.md
    - Invariants: Invariants.md
    - SchemaUtils: SchemaUtils.md
    - StateCache:
      - StateCache: StateCache.md
      - CachedDS: CachedDS.md
  - Contenders:
    - Contenders: contenders/index.md
